//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupDependencies.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupDependencies.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _150x150Logo_png {
            get {
                object obj = ResourceManager.GetObject("_150x150Logo_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _70x70Logo_png {
            get {
                object obj = ResourceManager.GetObject("_70x70Logo_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AddressParser {
            get {
                object obj = ResourceManager.GetObject("AddressParser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] antlr_runtime {
            get {
                object obj = ResourceManager.GetObject("antlr_runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Birds {
            get {
                object obj = ResourceManager.GetObject("Birds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FF99C8E9&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FF2B8DD4&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlueTheme {
            get {
                return ResourceManager.GetString("BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FFD6AA5B&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FFD6AA5B&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BrownTheme {
            get {
                return ResourceManager.GetString("BrownTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CharMap {
            get {
                object obj = ResourceManager.GetObject("CharMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colorpickerlib {
            get {
                object obj = ResourceManager.GetObject("colorpickerlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CoreAudioApi {
            get {
                object obj = ResourceManager.GetObject("CoreAudioApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer {
            get {
                object obj = ResourceManager.GetObject("Daytimer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Backgrounds {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Backgrounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Controls {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_DatabaseHelpers {
            get {
                object obj = ResourceManager.GetObject("Daytimer_DatabaseHelpers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_DockableDialogs {
            get {
                object obj = ResourceManager.GetObject("Daytimer_DockableDialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.0&quot; /&gt;
        ///  &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;!--&lt;gcAllowVeryLargeObjects enabled=&quot;true&quot; /&gt;
        ///		&lt;Thread_UseAllCpuGroups enabled=&quot;true&quot; /&gt;
        ///		&lt;GCCpuGroup enabled=&quot;true&quot; /&gt;
        ///		&lt;gcServer enabled=&quot;true&quot; /&gt;--&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.Runtime&quot; publicKeyToken=&quot;b03f5f7f11d50a3a&quot; cult [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Daytimer_exe {
            get {
                return ResourceManager.GetString("Daytimer_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Fonts {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Fonts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Functions {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Functions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Fundamentals {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Fundamentals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_GoogleCalendarHelpers {
            get {
                object obj = ResourceManager.GetObject("Daytimer_GoogleCalendarHelpers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_GoogleMapHelpers {
            get {
                object obj = ResourceManager.GetObject("Daytimer_GoogleMapHelpers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Help {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_ICalendarHelpers {
            get {
                object obj = ResourceManager.GetObject("Daytimer_ICalendarHelpers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Images {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Images", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_PrintHelpers {
            get {
                object obj = ResourceManager.GetObject("Daytimer_PrintHelpers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Search {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Styles {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Styles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_Toasts {
            get {
                object obj = ResourceManager.GetObject("Daytimer_Toasts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Application xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;VisualElements BackgroundColor=&quot;#0065AD&quot; ShowNameOnSquare150x150Logo=&quot;on&quot; ForegroundText=&quot;light&quot; Square150x150Logo=&quot;Assets\150x150Logo.png&quot; Square70x70Logo=&quot;Assets\70x70Logo.png&quot;/&gt;&lt;/Application&gt;.
        /// </summary>
        public static string Daytimer_VisualElementsManifest {
            get {
                return ResourceManager.GetString("Daytimer_VisualElementsManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Daytimer_WikiQuoteHelper {
            get {
                object obj = ResourceManager.GetObject("Daytimer_WikiQuoteHelper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DDay_Collections {
            get {
                object obj = ResourceManager.GetObject("DDay_Collections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DDay_iCal {
            get {
                object obj = ResourceManager.GetObject("DDay_iCal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DefaultNote {
            get {
                object obj = ResourceManager.GetObject("DefaultNote", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Demo_Main {
            get {
                object obj = ResourceManager.GetObject("Demo_Main", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FirstRun {
            get {
                object obj = ResourceManager.GetObject("FirstRun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.Runtime&quot; publicKeyToken=&quot;b03f5f7f11d50a3a&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirect oldVersion=&quot;0.0.0.0-2.5.19.0&quot; newVersion=&quot;2.5.19.0&quot; /&gt;
        ///      &lt;/dependentAssembly&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;System.Threading.Tasks&quot; publicKeyToken=&quot;b03f5f7f11d50a3a&quot; culture=&quot;neutral&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FirstRun_exe {
            get {
                return ResourceManager.GetString("FirstRun_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Generic1 {
            get {
                object obj = ResourceManager.GetObject("Generic1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Generic2 {
            get {
                object obj = ResourceManager.GetObject("Generic2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Generic3 {
            get {
                object obj = ResourceManager.GetObject("Generic3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gma_UserActivityMonitor {
            get {
                object obj = ResourceManager.GetObject("Gma_UserActivityMonitor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Google {
            get {
                object obj = ResourceManager.GetObject("Google", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Google_GData_AccessControl {
            get {
                object obj = ResourceManager.GetObject("Google_GData_AccessControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Google_GData_Calendar {
            get {
                object obj = ResourceManager.GetObject("Google_GData_Calendar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Google_GData_Client {
            get {
                object obj = ResourceManager.GetObject("Google_GData_Client", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Google_GData_Extensions {
            get {
                object obj = ResourceManager.GetObject("Google_GData_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FF9CB56E&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FF9CB56E&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GreenTheme {
            get {
                return ResourceManager.GetString("GreenTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FFFFFFFF&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FFCFCFCF&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Black&quot; Color=&quot;#FFFFFFFF&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;White&quot; Color=&quot;#FF2D2D2D&quot; /&gt;
        ///	&lt;Color x:Key=&quot;WhiteColor&quot;&gt;#FF2D2D2D&lt;/Color&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Gray&quot; Color=&quot;#FFE1E1E1&quot; /&gt;
        ///	&lt;Visibility x:Key=&quot;Backgroun [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HighContrastTheme {
            get {
                return ResourceManager.GetString("HighContrastTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iPhone {
            get {
                object obj = ResourceManager.GetObject("iPhone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] JumpTaskImages {
            get {
                object obj = ResourceManager.GetObject("JumpTaskImages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DDay.iCal library, its documentation, and its source code
        ///are Copyright © 2007 Douglas Day &lt;doug@ddaysoftware.com&gt;.
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or
        ///without modification, are permitted provided that the following
        ///conditions are met:
        ///
        ///    * Redistributions of source code must retain the above
        ///      copyright notice, this list of conditions and the
        ///      following disclaimer.
        ///      
        ///    * Redistributions in binary form must reproduce the above
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FFD57272&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FFAD3030&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MaroonTheme {
            get {
                return ResourceManager.GetString("MaroonTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Threading_Tasks {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Threading_Tasks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Threading_Tasks_Extensions {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Threading_Tasks_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Threading_Tasks_Extensions_Desktop {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Threading_Tasks_Extensions_Desktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_Windows_Shell {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Windows_Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_WindowsAPICodePack {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Microsoft_WindowsAPICodePack_Shell {
            get {
                object obj = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_Shell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Modern_FileBrowser {
            get {
                object obj = ResourceManager.GetObject("Modern_FileBrowser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nokia {
            get {
                object obj = ResourceManager.GetObject("Nokia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FFC899E9&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FF8D2BD4&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PurpleTheme {
            get {
                return ResourceManager.GetString("PurpleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RecurrenceGenerator {
            get {
                object obj = ResourceManager.GetObject("RecurrenceGenerator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RibbonControlsLibrary {
            get {
                object obj = ResourceManager.GetObject("RibbonControlsLibrary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///		xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///		xmlns:PresentationOptions=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation/options&quot;
        ///		xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; mc:Ignorable=&quot;PresentationOptions&quot;&gt;
        ///	&lt;!-- General --&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;Blue&quot; Color=&quot;#FF9B9B9B&quot; PresentationOptions:Freeze=&quot;True&quot; /&gt;
        ///	&lt;SolidColorBrush x:Key=&quot;TodayText&quot; Color=&quot;#FF2B2B2B&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SilverTheme {
            get {
                return ResourceManager.GetString("SilverTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] System_Net_Json {
            get {
                object obj = ResourceManager.GetObject("System_Net_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] System_Runtime {
            get {
                object obj = ResourceManager.GetObject("System_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] System_Threading_Tasks {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Tasks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Thought_vCards {
            get {
                object obj = ResourceManager.GetObject("Thought_vCards", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UpdateManager {
            get {
                object obj = ResourceManager.GetObject("UpdateManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.0&quot;/&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt;
        ///.
        /// </summary>
        public static string UpdateManager_exe {
            get {
                return ResourceManager.GetString("UpdateManager_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Windows {
            get {
                object obj = ResourceManager.GetObject("Windows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Wintellect_Threading {
            get {
                object obj = ResourceManager.GetObject("Wintellect_Threading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WpfAnimatedGif {
            get {
                object obj = ResourceManager.GetObject("WpfAnimatedGif", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
