#ifndef VERSIONING_H
#define VERSIONING_H

#include  "Build_Defs.h"


#define VERSION_MAJOR 1
#define VERSION_MINOR 0


#define VERSION_BUILD ( DAYS_SINCE_EPOCH )
#define VERSION_REVISION ( SECONDS_SINCE_MIDNIGHT / 2 )


#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)
#define VERSION_STRING TOSTRING(VERSION_MAJOR)"."TOSTRING(VERSION_MINOR)"."TOSTRING(VERSION_BUILD)"."TOSTRING(VERSION_REVISION)


#endif // VERSIONING_H
